name: Deploiement en Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Sync files to production
      run: rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no" ./ 192.168.1.53:/app/palanquee-app

    - name: Restart application
      run: ssh -o StrictHostKeyChecking=no ludo@192.168.1.53 'sudo systemctl restart palanquee-app'